### ISSUE TITLE
lazy solves

### ISSUE THREAD

**Issue by bannsec** [angr/rex#10]
I'm finding that in many larger examples of crash tracing, having LAZY_SOLVES enabled causes a state explosion. I see inside rex there are add and remove options being fed to tracer.

Suggest one of the following:

1. Remove LAZY_SOLVES by default in this
2. Make add and remove params argument for rex.Crash init

**Comment by zardus** [comment]
I think LAZY_SOLVES should definitely be removed by default in rex. In fact, one of these days, we'll get around to removing it by default globally in angr. Having it there by default does nothing but cause huge amounts of confusion.

**Comment by salls** [comment]
Let me look into what this does performance-wise before merging. I would expect no negative impacts but I'll still verify. 

I'm also kinda curious how the path explosion occurs. In CGC we follow the basic block trace so there can be no path explosion. I assume that's different for Linux binaries? Or maybe because in Linux there's too much that's not modelled perfectly to follow a qemu trace exactly?

**Comment by salls** [comment]
Okay I merged it. I didn't see any performance hit in my tests.
