### ISSUE TITLE
"list index out of range" for tracer

### ISSUE THREAD

**Issue by windhl** [angr/rex#14]
hi, I run rex with a simple stackoverflow sample, and I got error like this:

Traceback (most recent call last):
  File "ctf.py", line 4, in <module>
    crash = rex.Crash('./test64', 'A'*1024)
  File "/usr/local/lib/python2.7/dist-packages/rex/crash.py", line 114, in __init__
    prev, crash_state = self._tracer.run(constrained_addrs)
  File "/usr/local/lib/python2.7/dist-packages/tracer-0.1-py2.7.egg/tracer/tracer.py", line 508, in run
    branches = self.next_branch()
  File "/usr/local/lib/python2.7/dist-packages/tracer-0.1-py2.7.egg/tracer/tracer.py", line 271, in next_branch
    while self._addr_in_plt(self.trace[self.bb_cnt]):
IndexError: list index out of range

Hope your attentions, thanks.

**Comment by salls** [comment]
If you could upload an example that triggers this bug it would help me debug it. 
Rex has only had minimal testing on linux binaries, most of the work is on CGC so expect to run into at least a few more of these bugs.

**Comment by beraphin** [comment]
yeah I've got this problem too, because the input made the binary crash, and the crash happend in some functions such as memcpy which is out of binary, so the last few basics address is in plt area, however in next_branch() it just increase the bb_cnt while the basic address is in plt area without check if bb_cnt is bigger than len(self.trace), and in this case things would go wrong obviously, so I added a instruction in that while loop to make sure bb_cnt smaller than len(self.trace) , then everthing works fine.
