### ISSUE TITLE
How to use call_shellcode.py

### ISSUE THREAD

**Issue by Anhang512** [angr/rex#59]
Hello, I run the test function 'test_linux_stacksmash_64()' in test_rex.py. It successfully generate the exploit script called 'call_shellcode.py'.
But I don't know how to config the HOST and PORT parameter, and how to run the target program.
I would appreciate it if you could give me a hint.

**Comment by rhelmot** [comment]
This isn't particularly configurable, but what you can do is to instead of doing `exploit = crash.exploit()`, you can do `exploit = crash._prepare_exploit_factory(); exploit.shellcode.shellcode_args = {'host': HOST, 'port': PORT}; exploit.initialize()`. There is a TODO in crash.py to be able to parameterize these.

**Comment by Anhang512** [comment]
Thank you very much for your reply. 
I'm sorry I didn't describe the problem clearly. I want to ask **how to use the generated  exploit script to gain control of the target program**.
I have tried running the target program  on my Ubuntu 16.04 like this：
`socat tcp-listen:9999,reuseaddr,fork EXEC:./vuln_stacksmash,pty,raw`
And then I run the  exploit script like this:
` python call_shellcode.py 127.0.0.1 9999`
But the script command just receive a bunch of garbled without gaining interactive session.
